// regexnames writes std/src/regex_names.rs: every Unicode class name Go's
// regexp accepts in \p{...} (after its canonicalName), and the class it
// means, written for Rust's regex crate. Run with the Go that builds Hana:
//
//	go run . > ../../std/src/regex_names.rs
package main

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

// canonicalName is regexp/syntax's (Go 1.25).
func canonicalName(name string) string {
	var b strings.Builder
	first := true
	for i := 0; i < len(name); i++ {
		c := name[i]
		switch {
		case c == '_' || c == '-' || c == ' ':
			continue
		case first:
			if 'a' <= c && c <= 'z' {
				c -= 'a' - 'A'
			}
			first = false
		default:
			if 'A' <= c && c <= 'Z' {
				c += 'a' - 'A'
			}
		}
		b.WriteByte(c)
	}
	return b.String()
}

func main() {
	m := map[string]string{
		"Any":      `\p{Any}`,
		"Assigned": `\P{Cn}`,
		"Ascii":    `\x00-\x7F`,
		"Lc":       `\p{LC}`,
	}
	for k := range unicode.Categories {
		if _, ok := m[k]; !ok && canonicalName(k) == k {
			m[k] = `\p{` + k + `}`
		}
	}
	for k := range unicode.Scripts {
		if _, ok := m[k]; !ok && canonicalName(k) == k {
			m[k] = `\p{` + k + `}`
		}
	}
	for alias, actual := range unicode.CategoryAliases {
		c := canonicalName(alias)
		if _, ok := m[c]; !ok {
			m[c] = `\p{` + actual + `}`
		}
	}
	var names []string
	for k := range m {
		// Only what Go really accepts.
		if _, err := regexp.Compile(`\p{` + k + `}`); err == nil {
			names = append(names, k)
		}
	}
	sort.Strings(names)
	fmt.Println("// Generated by tools/regexnames from Go's regexp; do not edit.")
	fmt.Println()
	fmt.Println("/// (canonical name, the class in Rust's regex syntax, to go inside [...]).")
	fmt.Println("pub const UNICODE_CLASSES: &[(&str, &str)] = &[")
	for _, k := range names {
		fmt.Printf("    (%q, r\"%s\"),\n", k, m[k])
	}
	fmt.Println("];")
}
