[package]
name = "haru-cli"
description = "The haru command"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "haru_cli"
path = "src/lib.rs"

[[bin]]
name = "haru"
path = "src/main.rs"

[dependencies]
haru-core.workspace = true
haru-syntax.workspace = true
haru-std.workspace = true
haru-pkg-timezone = { path = "../../packages/timezone" }
haru-pkg-http-server = { path = "../../packages/http_server" }
haru-pkg-haneul = { path = "../../packages/haneul" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
sha2 = "0.10"
mimalloc = { version = "0.1", default-features = false }

[dev-dependencies]
haru-example-greet = { path = "../../examples/greet" }
haru-example-greet-c = { path = "../../examples/greet_c" }
