// errsgen writes Hana's runtime error catalogs (hana/errs) as Rust, so Haru
// prints exactly the same messages. The Go catalogs stay the only source;
// the generated file is never edited by hand.
//
//	go run . ../../crates/core/src/catalog.rs
//	go run . -check ../../crates/core/src/catalog.rs
package main

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/soumt-r/hana/errs"
)

func main() {
	args := os.Args[1:]
	check := len(args) > 0 && args[0] == "-check"
	if check {
		args = args[1:]
	}
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: errsgen [-check] <catalog.rs>")
		os.Exit(2)
	}
	want := render()
	if check {
		got, err := os.ReadFile(args[0])
		if err != nil || strings.ReplaceAll(string(got), "\r\n", "\n") != want {
			fmt.Fprintf(os.Stderr, "stale: %s (run errsgen)\n", args[0])
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(args[0], []byte(want), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func render() string {
	codes := errs.Export()
	sort.Slice(codes, func(i, j int) bool { return codes[i].Code < codes[j].Code })
	var b strings.Builder
	b.WriteString("// Code generated by tools/errsgen from hana/errs — DO NOT EDIT.\n\n")
	b.WriteString("/// (code, English, Korean, Japanese), sorted by code. Templates use Go's\n")
	b.WriteString("/// verbs (`%s`, `%d`, `%v`, `%[2]s`); see `error::go_format`.\n")
	b.WriteString("pub static CATALOG: &[(&str, &str, &str, &str)] = &[\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "    (%s, %s, %s, %s),\n", q(string(c.Code)), q(c.En), q(c.Ko), q(c.Ja))
	}
	b.WriteString("];\n\n")
	b.WriteString("/// The CLI heading of an uncaught runtime error: (English, Korean, Japanese).\n")
	fmt.Fprintf(&b, "pub static RUNTIME_LABEL: (&str, &str, &str) = (%s, %s, %s);\n",
		q(errs.LabelText(errs.English, errs.LabelRuntime)),
		q(errs.LabelText(errs.Korean, errs.LabelRuntime)),
		q(errs.LabelText(errs.Japanese, errs.LabelRuntime)))
	b.WriteString("\n/// The heading above syntax errors: (English, Korean, Japanese).\n")
	fmt.Fprintf(&b, "pub static PARSE_LABEL: (&str, &str, &str) = (%s, %s, %s);\n",
		q(errs.LabelText(errs.English, errs.LabelParseFailed)),
		q(errs.LabelText(errs.Korean, errs.LabelParseFailed)),
		q(errs.LabelText(errs.Japanese, errs.LabelParseFailed)))
	return b.String()
}

// q quotes s as a Rust string literal.
func q(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		default:
			if r < 0x20 {
				b.WriteString(`\u{` + strconv.FormatInt(int64(r), 16) + `}`)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
