// stdgen writes Hana's standard library catalog (hana/std: every module and
// function id with its Hari and Kanade names) as Rust, so Haru's standard
// modules carry exactly Hana's names and Haru knows which modules exist.
//
//	go run . ../../std/src/names.rs
//	go run . -check ../../std/src/names.rs
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/soumt-r/hana/std"
)

func main() {
	args := os.Args[1:]
	check := len(args) > 0 && args[0] == "-check"
	if check {
		args = args[1:]
	}
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: stdgen [-check] <names.rs>")
		os.Exit(2)
	}
	want := render()
	if check {
		got, err := os.ReadFile(args[0])
		if err != nil || strings.ReplaceAll(string(got), "\r\n", "\n") != want {
			fmt.Fprintf(os.Stderr, "stale: %s (run stdgen)\n", args[0])
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(args[0], []byte(want), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func render() string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/stdgen from hana/std — DO NOT EDIT.\n\n")
	b.WriteString("/// A standard module: its id, its (Hari, Kanade) names, whether it needs the\n")
	b.WriteString("/// operating system (files, network), and its functions: (id, Hari, Kanade).\n")
	b.WriteString("pub struct StdModule {\n    pub id: &'static str,\n    pub names: (&'static str, &'static str),\n    pub native_only: bool,\n    pub functions: &'static [(&'static str, &'static str, &'static str)],\n}\n\n")
	b.WriteString("pub static HANA_STD: &[StdModule] = &[\n")
	for _, m := range std.Modules {
		fmt.Fprintf(&b, "    StdModule {\n        id: %s,\n        names: (%s, %s),\n        native_only: %v,\n        functions: &[\n",
			strconv.Quote(m.ID), strconv.Quote(std.ModuleName(std.Hari, m.ID)), strconv.Quote(std.ModuleName(std.Kanade, m.ID)), m.NativeOnly)
		for _, f := range m.Functions {
			fmt.Fprintf(&b, "            (%s, %s, %s),\n", strconv.Quote(f),
				strconv.Quote(std.FunctionName(std.Hari, f)), strconv.Quote(std.FunctionName(std.Kanade, f)))
		}
		b.WriteString("        ],\n    },\n")
	}
	b.WriteString("];\n")
	return b.String()
}
