/// Token kinds. The same set for every language: the lexer maps each
/// language's words onto them (Hana's `token` package).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Eof,
    Illegal,
    Indent,
    Dedent,

    Ident,
    Int,
    Str,
    Var,
    Function,
    Type,
    TemplateString,
    Compare,
    Op,
    TypeIn,
    Particle,

    Colon,
    Assign,
    LBracket,
    RBracket,
    LParen,
    RParen,
    LBrace,
    RBrace,
    Comma,

    KwPrint,
    KwInput,
    KwMake,
    KwInterface,
    KwClass,
    KwImplements,
    KwIf,
    KwElse,
    KwElif,
    KwConstruct,
    KwDoAs,
    KwBase,
    KwGetter,
    KwSetter,
    KwFront,
    KwBack,
    KwAdd,
    KwSub,
    KwExecute,
    KwMustHave,
    KwNull,
    KwReturn,
    KwBreak,
    KwLoop,
    KwPush,
    KwPop,
    KwPopped,
    KwTry,
    KwCatch,
    KwFinally,
    KwThrow,
    KwImport,
    KwFrom,
    KwTrue,
    KwFalse,
    KwParent,
    KwOuter,
    KwNew,
    KwSelf,
    KwSwitch,
    KwCase,
    KwDefault,
    KwFallthrough,
    KwAnd,
    KwOr,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Token<'a> {
    pub kind: Kind,
    /// The source text (empty for INDENT/DEDENT/EOF).
    pub lit: &'a str,
    /// 1-based line.
    pub line: u32,
    /// 0-based column in characters.
    pub col: u32,
}
